### PR TITLE
Ana/add docker scripts

### PR DESCRIPTION
**Pull request by Bitcoinera**
Here I add some useful scripts to handle the docker containers.

I have some doubts whether the scripts commands to run every single container shouldn't be just the container name instead of `docker:<container-name>`.  Especially if all our project is going to be using them... but I think I remember you said the dockerization is only for the first milestone or something like that.

In that case we should keep the scripts as they are now, so they stay relevant & concrete.

I also fixed a typo and also updated the README

Thank you! 🚀

### CODE REVIEW

**Comment by derfredy** [comment]
I'd create a symlink in your Windows for your docker-composer.exe to point to standard docker-composer linux binary (without ".exe"). Thus your scripts would be worldwide compatible.

**Comment by Bitcoinera** [comment]
> I'd create a symlink in your Windows for your docker-composer.exe to point to standard docker-composer linux binary (without ".exe"). Thus your scripts would be worldwide compatible.

Oh true. Yes, now I realize this is an issue. Only have the first one converted xD

**Comment by Bitcoinera** [comment]
> > I'd create a symlink in your Windows for your docker-composer.exe to point to standard docker-composer linux binary (without ".exe"). Thus your scripts would be worldwide compatible.
> 
> Oh true. Yes, now I realize this is an issue. Only have the first one converted xD

Done!

**Comment by Bitcoinera** [comment]
> Tested locally. It works!
> I'd suggest to include a "npm stop docker" script to stop all containers.

Good suggestion! I will!

**Pull request merged**
