### PR TITLE
Ana/fix the staking crawler

### LINKED ISSUE #83: Fix staking crawlers for update (polkadot/api 1.6.2)
We need to fix the currently failing staking crawler so it gets updated with the new methods/syntax from the latest @polkadot/api.

I can do it! :muscle:

### PR DESCRIPTION
**Pull request by Bitcoinera**
Closes #83 

**Description:**

Fixing the staking crawler to work with the latest runtime release for Kusama

Thank you! 🚀

---

For contributor:

- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by Bitcoinera** [comment]
It is working now.

Can you please check the JSON in intention_staking? It is the only thing I am not sure about

**Comment by Bitcoinera** [comment]
Oops, I also need to change how currentElected (eraValidatorsList) is being fetched

**Comment by derfredy** [comment]
Hey!  This is working!  I have just tested!
It seems promising.
Just a comment. Table validator_staking has only one huge element that seems to hangs hasura for some time when I browse around it. Do we need such big objets?

**Comment by Bitcoinera** [comment]
> Do we need such big objets?

@mariopino , please test what is being saved & what we actually need for Polkastats

**Comment by mariopino** [comment]
> Hey! This is working! I have just tested!
> It seems promising.
> Just a comment. Table validator_staking has only one huge element that seems to hangs hasura for some time when I browse around it. Do we need such big objets?
> The same happens with intention_staking

Hey @derfredy , the data in db is actually right, this is the correct behaviour. Yep, staking object is big, it stores staking info for 180 validators and their respective nominators, but we only fetch it at every session change (every hour).

**Pull request merged**
