### PR TITLE
[WIP] Comment out the build process and download the binary

### LINKED ISSUE #76: Upload compiled offline-phragmen to the same forked repo
We should upload a compiled version of phragmen binary somewhere as it causes a lot of time lose each time we rebuild from scratch. 

What do you think it is a good place for it?
@Bigomby  @mariopino  @Scriptonita @Bitcoinera

### PR DESCRIPTION
**Pull request by derfredy**
Closes #76

**Description:**

Temporary disable the default and slow rust build process of phragmen binary.

Waiting for @Bigomby to accept the PR in his personal repo.

Thank you! 🚀

---

For contributor:

- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by Bitcoinera** [comment]
> Waiting for @Bigomby to accept the PR in his personal repo.

Why? He can just merge from develop right?

**Comment by derfredy** [comment]
We finally agreed to upload the binary in a "release" instead of my first PR attempt.

**Comment by Bigomby** [comment]
The binary is ready https://github.com/Bigomby/offline-phragmen/releases/tag/0.1.0

**Comment by derfredy** [comment]
Thanks! This PR is ready to merge.

**Pull request merged**
